name: Laravel Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, exif, pcntl, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
          coverage: none

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Setting sqlite
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env

      - name: Create SQLite database file
        run: |
          mkdir -p database
          touch database/database.sqlite
          chmod -R 777 database

      - name: Verify SQLite file
        run: ls -l database/database.sqlite

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate application key
        run: php artisan key:generate

      - name: Migrate
        run: php artisan migrate:fresh

      - name: Run tests
        run: php artisan test